contact/urls.py
from django.urls import path
from contact import views

app_name = 'contact'

urlpatterns = [
    path('search/', views.search, name='search'),
    path('', views.index, name='index'),
    
    # Contact (CRUD)
    path('contact/<int:contact_id>/detail/', views.contact, name='contact'),
    path('contact/<int:contact_id>/update/', views.update, name='update'),
    path('contact/<int:contact_id>/delete/', views.delete, name='delete'),
    path('contact/create/', views.create, name='create'),
    
    # user (CRUD)
    path('user/register/', views.register, name='register'),
    path('user/login/', views.login_views, name='login'),
    path('user/logout/', views.logout_views, name='logout'),
    path('user/update/', views.user_update, name='user_update'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('contact.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

contact/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# ID (primary key - gerado automaticamente) -> Valor que busca na base de dados
# first_name(string) - last_name(string) -  phone(string) - email(email) - created_date(date) - description(text)
# category(foreing key) - show(boolean) - picture(image)
# DEPOIS 
# - owner(foreing key) 

class Category(models.Model):
    class Meta:
        verbose_name = 'Category'   # O que mostrar quando houver uma categoria
        verbose_name_plural = 'Categories'  # O que mostrar quando estiver no plural
    
    name = models.CharField(max_length=30)
    
    def __str__(self) -> str:   # O  que será mostrado na admin do model
        return f'{self.name}'

class Contact(models.Model):
    first_name = models.CharField(max_length=40)
    last_name = models.CharField(max_length=20, blank=True)
    phone = models.CharField(max_length=25)
    email = models.EmailField(max_length=254, blank=True)
    created_date = models.DateTimeField(default=timezone.now)   # Django registra automaticamente a hora de criação.
    description = models.TextField(blank=True)
    show = models.BooleanField(default=True)
    picture = models.ImageField(blank=True, upload_to='pictures/%Y/%m')
    category = models.ForeignKey(   # Relacão com classe Categoria
        Category, 
        on_delete=models.SET_NULL,
        blank=True, null=True)
    owner = models.ForeignKey(   # Relacão com classe Categoria
        User, 
        on_delete=models.CASCADE,   # Apaga tudo quando o usuario é deletado
        blank=True, null=True)
    
    def __str__(self) -> str:   # O  que será mostrado na admin do model
        return f'{self.first_name} {self.last_name}'
    
    

contact/forms.py
from django.core.exceptions import ValidationError
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import password_validation

from . import models


class ContactForm(forms.ModelForm):
    first_name = forms.CharField(
        widget = forms.TextInput(
            attrs={
                'placeholder': 'Write the first name',
            }
        ),
        help_text="Don't write nickname.",
    )
    picture = forms.ImageField(
        widget = forms.FileInput(
            attrs={
                'accept': 'image/*',
            }
        ),
        required=False,
    )
    class Meta:
        model = models.Contact
        fields = 'first_name', 'last_name', 'phone', 'email', 'description', 'category', 'picture'
        
        
    def clean(self):
        cleaned_data = super().clean()
        first_name = cleaned_data.get('first_name')
        last_name = cleaned_data.get('last_name')
        
        if first_name == last_name:
            self.add_error(
                'last_name',
                ValidationError(
                    "The last name cannot be the same as the first. Try again",
                    code='invalid'
                )
            )
        

        return cleaned_data
        
    def clean_first_name(self):
            first_name = self.cleaned_data.get('first_name')
            if first_name == 'ABC':
                raise ValidationError(
                    "Don't enter ABC",
                    code = 'invalid'
                )
            return first_name

class RegisterForm(UserCreationForm):
    first_name = forms.CharField(
        required=True,
        min_length=3
    )
    last_name = forms.CharField(
        required=True,
        min_length=3
    )
    email = forms.EmailField(
        required=True,  
    )
    class Meta:
        model = User
        fields = 'first_name', 'last_name', 'email', 'username', 'password1', 'password2',
    
    def clean_email(self):
        email = self.cleaned_data.get('email')
        
        if User.objects.filter(email=email).exists():
            raise ValidationError(
                'This email already exists',
                code='invalid'
            )
        
        return email
    
class RegisterUpdateForm(forms.ModelForm):
    first_name = forms.CharField(
        min_length=2,
        max_length=30,
        required=True,
        help_text="Required.",
        error_messages={
            'min_length': 'Please, add more than 2 letters'
        }
    )
    last_name = forms.CharField(
        min_length=2,
        max_length=30,
        required=True,
        help_text="Required.",
        error_messages={
            'min_length': 'Please, add more than 2 letters'
        }
    )
    password1 = forms.CharField(
        label='Password',
        strip=False,
        required=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        help_text=password_validation.password_validators_help_text_html(),
    )
    password2 = forms.CharField(
        label='Password 2',
        strip=False,
        required=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        help_text= "Use the same password as before",
    )
    class Meta:
        model = User
        fields = 'first_name', 'last_name', 'email', 'username', 
      
      
    def save(self, commit=False): 
        cleaned_data = self.cleaned_data
        user = super().save(commit=False) 
        
        password = cleaned_data.get('password1')
        
        if password:
            user.set_password(password)
            
        if commit:
            user.save()
            
        return user
      
    def clean(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        
        if password1 or password2:
            if password1 != password2:
                self.add_error(
                    'password2',
                    ValidationError('The passwords are diferent')
                )
                
                
        return super().clean()  
      
    def clean_email(self):
        email = self.cleaned_data.get('email')
        email_login = self.instance.email
        
        if email != email_login:
            if User.objects.filter(email=email).exists():
                raise ValidationError(
                    'This email already exists',
                    code='invalid'
                )
            
            return email
        
    def clean_password1(self):
        password1 = self.cleaned_data.get('password1')
        
        if password1:
            try:
                password_validation.validate_password(password1)
            except ValidationError as errors:
                self.add_error(
                    'password1',
                    ValidationError(errors)
                )
        
        return password1

contact/views.py
from django.shortcuts import render

def index(request):
    return render(
        request,
        'contact/index.html',
    )

contact/views/contact_forms.py
from django.contrib import messages
from contact.decorators import login_required_with_message
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse

from contact.forms import ContactForm    
from contact.models import Contact

@login_required_with_message('You need to be logged in to create a contact')  
def create(request):
    form_action = reverse('contact:create')
    if request.method == 'POST':
        form = ContactForm(request.POST, request.FILES)
        
        context = {
        'form': form ,
        'form_action': form_action,
        'title': 'Create Contact',
        }  
        
        # Caso o formulário seja válido, então será redirecionado para a página update
        if form.is_valid():
            contact = form.save(commit=False)     # Salva os dados na base de dados
            contact.owner = request.user
            contact.save()
            messages.success(request, 'Contact created')
            return redirect('contact:update', contact_id=contact.pk)
    
        return render(
        request,
        'contact/create.html',
        context
        )
    
    context = {
        'form': ContactForm(),
        'title': 'Create Contact',
    }  
    
    return render(
        request,
        'contact/create.html',
        context
    )
  
@login_required_with_message('You need to be logged in to update a contact')     
def update(request, contact_id):
    contact = get_object_or_404(Contact, pk=contact_id, show=True, owner=request.user)  # Busca do contato ou erro 404
    form_action = reverse('contact:update', args=(contact_id, ))
    
    if request.method == 'POST':
        form = ContactForm(request.POST, request.FILES, instance=contact)
        
        context = {
        'form': form ,
        'form_action': form_action,
        'title': 'Update Contact',
        }  
        
        # Caso o formulário seja válido, então será redirecionado para a página update
        if form.is_valid():
            contact = form.save()     # Salva os dados na base de dados
            messages.success(request, 'Updated contact')
            return redirect('contact:update', contact_id=contact.pk)
    
        return render(
        request,
        'contact/create.html',
        context
        )
    
    context = {
        'form': ContactForm(instance=contact),
        'title': 'Update Contact',
    }  
    
    return render(
        request,
        'contact/create.html',
        context
    )

@login_required_with_message('You need to be logged in to delete a contact')        
def delete(request, contact_id):
    contact = get_object_or_404(Contact, pk=contact_id, show=True, owner=request.user)  # Busca do contato ou erro 404
    confirmation = request.POST.get('confirmation', 'no')


    if confirmation == 'yes':
        contact.delete()
        messages.success(request, 'Contact deleted')
        return redirect('contact:index')
        
    return render (
        request,
        'contact/delete.html',
        {
            'contact':contact,
            'confirmation': confirmation
        }
    )

contact/views/contact_views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q
from django.core.paginator import Paginator
from contact.models import Contact

def index(request):
    contacts = Contact.objects.filter(show=True).order_by('-id')
    
    paginator = Paginator(contacts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    
    context = {
        'page_obj': page_obj ,
        'site_title': 'Contacts -'
    }  
    
    return render(
        request,
        'contact/index.html',
        context
    )
    
def search(request):
    search_value = request.GET.get('q', '').strip()
    
    if search_value == '':
        return redirect('contact:index')    # Quando não acha o valor, redireciona para outra página
    
    contacts = Contact.objects.\
        filter(show=True)\
            .filter(
            Q(first_name__icontains=search_value) |     # Usa para fazer pesquisa OU
            Q(phone__icontains=search_value) |          # Usa para fazer pesquisa OU
            Q(email__icontains=search_value) |          # Usa para fazer pesquisa OU
            Q(last_name__icontains = search_value))\
                .order_by('first_name')
                
    paginator = Paginator(contacts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    
    context = {
        'page_obj': page_obj ,
        'site_title': 'Contacts -'
    }  
    
    return render(
        request,
        'contact/index.html',
        context
    )   
    
def contact(request, contact_id):
    single_contact = get_object_or_404(Contact, pk=contact_id, show=True)
    
    context = {
        'contact': single_contact,
        'site_title': f'{single_contact.first_name} -'
    }  
    
    return render(
        request,
        'contact/contact.html',
        context
    )

contact/views/user_forms.py
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import auth
from django.shortcuts import render, redirect
from contact.decorators import login_required_with_message

from contact.forms import RegisterForm, RegisterUpdateForm

def register(request):
    form = RegisterForm()

    if request.method == 'POST':
        form = RegisterForm(request.POST)

        if form.is_valid():
            form.save()
            messages.success(request, 'Registered user')
            return redirect('contact:login')

    return render(
        request,
        'contact/register.html',
        {
            'form': form,
            'title': 'Register User'
        }
    )

def login_views(request):
    form = AuthenticationForm(request)
    
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        
        if form.is_valid():
            user = form.get_user()
            auth.login(request, user)
            messages.success(request, 'Logged in successfully!')
            return redirect('contact:index')
        
        messages.error(request, 'Loggin failed')
    
    return render(
        request,
        'contact/login.html',
        {
            'form': form,
            'title': 'Login User'
        }
    )
    
@login_required_with_message('You need to be logged in to logout')   
def logout_views(request):
    confirmation = request.POST.get('confirmation', 'no')
     
    if confirmation == 'yes':
        auth.logout(request)
        messages.success(request, 'User logged out')
        return redirect('contact:login')
    
    return render(
        request,
        'contact/logout.html',
        {
            'title': 'Logout User'
        }
    )

@login_required_with_message('You need to be logged in to update a user')      
def user_update(request):
    form = RegisterUpdateForm(instance=request.user)
    
    if request.method == 'POST':
        form = RegisterUpdateForm(instance=request.user, data=request.POST)
        
        if form.is_valid():
            form.save()
            messages.success(request, 'User updated')
            return redirect('contact:index')
            
        messages.error(request, 'Update failed')
        
    return render(
        request,
        'contact/register.html',
        {
            'form': form,
            'title': 'Update User'
        }
    )

contact/templates/contact/contact.html
{% extends "global/base.html" %}

{% block content %}
<div class="single-contact">
    <h1 class="single-contact-name">
        {{contact.first_name}} {{contact.last_name}}
    </h1>

    <p><b>ID: </b> {{contact.id}}</p>
    <p><b>Phone: </b> {{contact.phone}}</p>
    <p><b>E-mail: </b> {{contact.email}}</p>
    <p><b>Created Date: </b> {{contact.created_date}}</p>
    <p><b>Description: </b> {{contact.description}}</p>
    <p><b>Category: </b> {{contact.category.name}}</p>

    {% if contact.picture %}
    <p>
        <img src="{{ contact.picture.url }}" alt=" {{contact.first_name}} {{contact.last_name}}">
    </p>
    {% endif %}

    {% if request.user == contact.owner %}
    <div class="contact-links">
        <a class="btn btn-link" href="{% url 'contact:update' contact.id %}">Update</a>

        <form action="{% url 'contact:delete' contact.id %}" method="POST">
            {% csrf_token %}

            <button class="btn btn-link btn-delete" type="submit">Delete</button>
        </form>
    </div>
    {% endif %}
</div>
{% endblock content %}

contact/templates/contact/create.html
{% extends "global/base.html" %}

{% block content %}
<div class="form-wrapper">
    <h2>{{ title }}</h2>
    <form action="{{ form_action }}" method="POST" enctype="multipart/form-data">

        {% csrf_token %} <!--Proteção do Django-->

        <div class="form-content">
            {% for field in form %}
            <div class="form-group">
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{field}}
                {{field.errors}} <!--Para mostrar caso haja erros-->

                {% if field.help_text %}
                    <p class="help-text">{{ field.help_text }}</p>
                {% endif %}
            </div>
                {% if field.name == 'picture' and field.value.url %}
                    <div class="form-group">
                    <img src="{{field.value.url}}" alt="">
                    </div>
                {% endif %}
            {% endfor %}
            {% if field.non_field_errors %}
            <div class="form-content">
                <div class="form-group">
                    <div class="message error">
                        {{ form.non_field_errors }}
                    </div>
                </div>
            </div>
            {% endif %}
        </div>

        <div class="form-content">
            <div class="form-group">
                <button type="submit" class="btn">Send</button>
            </div>
        </div>
    </form>
</div>
{% endblock content %}

contact/templates/contact/delete.html
{% extends "global/base.html" %}

{% block content %}
    <div class="form-wrapper">  
        <h2>Do you want to delete this contact?</h2>
        <div class="contact-links">
            <a class="btn btn-link" href="{% url 'contact:contact' contact.id %}">Back</a>
    
            <form action="{% url 'contact:delete' contact.id %}" method="POST">
                {% csrf_token %}
                
                <input type="hidden" name="confirmation" value="yes">
                <button class="btn btn-link btn-delete" type="submit">Confirm</button>
            </form>
        </div>
    </div>
{% endblock content %}

contact/templates/contact/index.html
{% extends "global/base.html" %}
{% block content %}
{% if page_obj %}
<div class="responsive-table">
    <table class="contacts-table">
        <!-- Espécie de Título de Cabeçalho -->
        <caption class="table-caption">
            Contacts
        </caption>
        <!-- Espécie de Cabeçalho, onde mostra o que titulo de cada coluna -->
        <thead>
            <tr class="table-row table-row-header">
                <th class="table-header">ID</th>
                <th class="table-header">First Name</th>
                <th class="table-header">Last Name</th>
                <th class="table-header">Phone</th>
                <th class="table-header">E-Mail</th>
            </tr>
        </thead>

        <tbody>
            {% for contact in page_obj %}
            <tr class="table-row">
                <td class="table-cel">
                    <a href="{% url "contact:contact" contact.id %}" class="table-link">
                        {{contact.id}}
                    </a>
                </td>
                <td class="table-cel">
                    {{contact.first_name}}
                </td>
                <td class="table-cel">
                    {{contact.last_name}}
                </td>
                <td class="table-cel">
                    {{contact.phone}}
                </td>
                <td class="table-cel">
                    {{contact.email}}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% else %}
<div class="single-contact">
    <h1 class="single-contact-name">
        Contact not found
    </h1>
</div>
{% endif %}
{% endblock content %}

contact/templates/contact/login.html
{% extends "global/base.html" %}

{% block content %}
<div class="form-wrapper">
    <h2>{{ title }}</h2>
    
    {% if user.is_authenticated %}
        <p>
            You are authenticated as {{user.username}}. <br><br>
            To log out, click <a class="btn" id="btn-login" href="{% url 'contact:logout' %}">here</a>.
        </p>
    {% else %}
        {% include "contact/partials/_user-form.html" %}
    {% endif %}
</div>
{% endblock content %}

contact/templates/contact/logout.html
{% extends "global/base.html" %}

{% block content %}
    <div class="form-wrapper">  
        <h2>Are you sure you want to log out?</h2>
        <div class="contact-links">
            <a class="btn btn-link" href="{% url 'contact:index'%}">No</a>
            <form action="{% url 'contact:logout' %}" method="POST">
                {% csrf_token %}
                
                <input type="hidden" name="confirmation" value="yes">
                <button class="btn btn-link btn-delete" type="submit">Yes</button>
            </form>
        </div>
    </div>
{% endblock content %}

contact/templates/contact/register.html
{% extends "global/base.html" %}

{% block content %}
<div class="form-wrapper">
    <h2>{{ title }}</h2>
    
    {% include "contact/partials/_user-form.html" %}
</div>
{% endblock content %}